DEST=	/usr/local/bin
MANDIR=	/usr/man/manl
OWNER=	bin
GROUP=	staff
CFLAGS=	-O

all:	plotdb iplotdb

install: all
	install -s -o ${OWNER} -g ${GROUP} plotdb ${DEST}
	install -s -o ${OWNER} -g ${GROUP} iplotdb ${DEST}

cmp:	all
	cmp plotdb /usr/bin/plotdb
	cmp iplotdb /usr/bin/iplotdb

plotdb.o: plotdb.h
plotdb:	 plotdb.o
	cc plotdb.o -o plotdb -lloc

iplotdb.o: iplotdb.h plotdb.h
iplotdb: iplotdb.o 
	cc -O iplotdb.o -o iplotdb -lloc

install-man:
	install -c -o ${OWNER} -g ${GROUP} plotdb.1g ${MANDIR}/plotdb.l
	install -c -o ${OWNER} -g ${GROUP} plotfil.5 ${MANDIR}/plotfil.l

clean:
	rm -f *.o plotdb iplotdb core pltfil
