#define FILENAME	"*filename:  %s\n"
#define ERROR		"*invalid plot command:  %c\n"
#define MOVE		"move\t%5d\t%5d\n"
#define DRAW		"draw\t%5d\t%5d\n"
#define BREAK		"break\n"
#define ERASE		"erase\n"
#define FATBASE		"fatbase\t%5d\n"
#define WINDOW		"window\t%5d\t%5d\t%5d\t%5d\n"
#define XHAIRS		"xhairs\n"
#define PURGE		"purge\n"
#define NOOP		"no-op\n"
#define CIRCLE		"circle:\txmask%5d\tymask%5d\tX%5d\tY%5d\tradius%5d\n"
#define	COLOR		"Color:\tred%5d\tgreen%5d\tblue%5d\n"
#define LINE		"line:\tnpts%5d\n"
#define POINT		"point\t%5d\t%5d\n"
#define AREAKEY		"area:\txmask%5d\tymask%5d\tnpts%5d\n"
#define AREAWARN	"*error:  zero is not a valid shade specification\n"
#define AREAPOINT	"vertex\t%5d\t%5d\n"
#define AREAERROR	"*error:  polygon does not close\n"
#define APATKEY		"Apat:\tpattern%5d\tnpts%5d\n"
#define TEXTERROR	"*error:  invalid text key:  0%o\n"
#define TEXTKEY		"text:\tsize%5d\torient%5d\tfont%3d\n"
#define TEXTNUM		"0%o"
#define TEXTCHAR	" %c"
#define TEXTNESC	"ESC \\0%o"
#define TEXTCESC	"ESC %c"
#define TEXTOUT		"%s\n"
#define TEXTEND		"end of text\n"
#define RASTHEAD	"raster:\n"
#define RASTKEY		"count%5d\toffset%5d\n"
#define RASTWORD	"0%06o\n"
#define RASTEND		"end of raster\n"
